#!/bin/bash
#SBATCH --job-name=envCreate_v1.0
#SBATCH --output=/home/scur2640/uvadlc_practicals_2024/assignment1/logs/envCreate_output_%j.txt
#SBATCH --error=/home/scur2640/uvadlc_practicals_2024/assignment1/logs/envCreate__error_%j.txt
#SBATCH --time=03:00:00
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=32G
#SBATCH --gres=gpu:1

set -x  # Enable debug mode for detailed output

# loading/activating modules
module purge
module load 2023
module load Anaconda3/2023.07-2

# create the environment
conda env create -f /home/scur2640/uvadlc_practicals_2024/dl2024_gpu.yml
conda activate dl2024

# moving to project directory
cd /home/scur2640/uvadlc_practicals_2024