#!/bin/bash
#SBATCH --job-name=envCreate_v1.0
#SBATCH --output=/home/scur2640/uvadlc_practicals_2024/assignment1/logs/runTraining_output_%j.txt
#SBATCH --error=/home/scur2640/uvadlc_practicals_2024/assignment1/logs/runTraining_error_%j.txt
#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --gres=gpu:1

set -x  # Enable debug mode for detailed output

# loading/activating modules
module load 2023
module load Anaconda3/2023.07-2
conda init bash
source ~/.bashrc

# moving to project directory
cd /home/scur2640/uvadlc_practicals_2024

# create the environment
conda activate dl2024

# running the training script
python /home/scur2640/uvadlc_practicals_2024/assignment1/train_mlp_numpy.py